class TransactionModel {
  final String?
  id; // Nullable because it will be generated by Firestore/Local DB
  final String merchant;
  final double amount;
  final String date; // Using string for now to match YYYY-MM-DD
  final String category;
  final bool isImpulse;
  final bool isIncome;
  final bool isPending;
  final String? note;
  final int timestamp; // epoch for sorting

  // Phase 2 AI Metadata Fields
  final String? subcategory;
  final String? intent; // e.g., Recreational, Convenience
  final String? necessity; // e.g., High, Medium, Low
  final String? spendingType; // e.g., Necessary, Discretionary
  final String? aiSuggestedCategory;
  final String? aiReclassificationReason;

  TransactionModel({
    this.id,
    required this.merchant,
    required this.amount,
    required this.date,
    required this.category,
    required this.isImpulse,
    this.isIncome = false,
    this.isPending = false,
    this.note,
    required this.timestamp,
    this.subcategory,
    this.intent,
    this.necessity,
    this.spendingType,
    this.aiSuggestedCategory,
    this.aiReclassificationReason,
  });

  // Convert to Map for SQLite
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'merchant': merchant,
      'amount': amount,
      'date': date,
      'category': category,
      'isImpulse': isImpulse ? 1 : 0, // SQLite doesn't have booleans
      'isIncome': isIncome ? 1 : 0,
      'isPending': isPending ? 1 : 0,
      'note': note,
      'timestamp': timestamp,
      'subcategory': subcategory,
      'intent': intent,
      'necessity': necessity,
      'spendingType': spendingType,
      'aiSuggestedCategory': aiSuggestedCategory,
      'aiReclassificationReason': aiReclassificationReason,
    };
  }

  // Convert from SQLite Map
  factory TransactionModel.fromMap(Map<String, dynamic> map) {
    return TransactionModel(
      id: map['id']?.toString(),
      merchant: map['merchant'] ?? '',
      amount: map['amount']?.toDouble() ?? 0.0,
      date: map['date'] ?? '',
      category: map['category'] ?? 'Other',
      isImpulse: (map['isImpulse'] == 1 || map['isImpulse'] == true),
      isIncome: (map['isIncome'] == 1 || map['isIncome'] == true),
      isPending: (map['isPending'] == 1 || map['isPending'] == true),
      note: map['note']?.toString(),
      timestamp: map['timestamp'] ?? 0,
      subcategory: map['subcategory']?.toString(),
      intent: map['intent']?.toString(),
      necessity: map['necessity']?.toString(),
      spendingType: map['spendingType']?.toString(),
      aiSuggestedCategory: map['aiSuggestedCategory']?.toString(),
      aiReclassificationReason: map['aiReclassificationReason']?.toString(),
    );
  }
}
