// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNM64FxDJE3XUIQj33tS7UxXyajdhoifQ',
    appId: '1:666400777649:web:c53ab096ef65af7d4a0990',
    messagingSenderId: '666400777649',
    projectId: 'finsnap-3ba0c',
    authDomain: 'finsnap-3ba0c.firebaseapp.com',
    storageBucket: 'finsnap-3ba0c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT9_t-rQPuy9K6HHvuuwWyy4yBuuTDHcQ',
    appId: '1:666400777649:android:52570777b51fbaa84a0990',
    messagingSenderId: '666400777649',
    projectId: 'finsnap-3ba0c',
    storageBucket: 'finsnap-3ba0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBOWzZINlX72LI-jbBiondM9baJs3MJFw',
    appId: '1:666400777649:ios:5781a25bedf96ca94a0990',
    messagingSenderId: '666400777649',
    projectId: 'finsnap-3ba0c',
    storageBucket: 'finsnap-3ba0c.firebasestorage.app',
    iosBundleId: 'com.example.budgetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBOWzZINlX72LI-jbBiondM9baJs3MJFw',
    appId: '1:666400777649:ios:5781a25bedf96ca94a0990',
    messagingSenderId: '666400777649',
    projectId: 'finsnap-3ba0c',
    storageBucket: 'finsnap-3ba0c.firebasestorage.app',
    iosBundleId: 'com.example.budgetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNM64FxDJE3XUIQj33tS7UxXyajdhoifQ',
    appId: '1:666400777649:web:602e5e6819dcf5614a0990',
    messagingSenderId: '666400777649',
    projectId: 'finsnap-3ba0c',
    authDomain: 'finsnap-3ba0c.firebaseapp.com',
    storageBucket: 'finsnap-3ba0c.firebasestorage.app',
  );
}
